# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-31 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesseract_ocr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegistrationImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('internal_reference', models.CharField(editable=False, max_length=100, verbose_name='Internal Reference')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='OCR_image/input/', verbose_name='Input BusinessRegistrationImage')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
            ],
            options={
                'verbose_name': 'BusinessRegistrationImageFile',
                'verbose_name_plural': 'BusinessRegistrationImageFiles',
                'ordering': ['id'],
            },
        ),
    ]
