# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-02 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesseract_ocr', '0002_businessregistrationimagefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRegistrationOCRText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='OCR text')),
                ('lang', models.TextField(default='kor+eng', verbose_name='Language')),
                ('execution_time', models.IntegerField(editable=False, null=True, verbose_name='Execution Time')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesseract_ocr.BusinessRegistrationImageFile')),
            ],
            options={
                'verbose_name': 'BusinessRegistrationOCRText',
                'verbose_name_plural': 'BusinessRegistrationOCRTexts',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='ocrtext',
            name='lang',
            field=models.TextField(default='kor+eng', verbose_name='Language'),
        ),
    ]
