# Generated by Django 3.2.6 on 2022-07-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesseract_ocr', '0004_auto_20220722_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='ocr_engine',
            field=models.CharField(default='Tesseract', max_length=50, verbose_name='OCR Engine'),
        ),
        migrations.AddField(
            model_name='ocrtext',
            name='ocr_engine',
            field=models.CharField(default='Tesseract', max_length=50, verbose_name='OCR Engine'),
        ),
    ]
